### ISSUE TITLE
Identity: documentation

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-protocol-eth#29]
of the .sol file: https://github.com/AdExNetwork/adex-protocol-eth/blob/master/contracts/extra/Identity.sol

and of the libraries that come with it:

https://github.com/AdExNetwork/adex-protocol-eth/blob/master/js/Identity.js
https://github.com/AdExNetwork/adex-protocol-eth/blob/master/js/IdentityDeploy.js

**Comment by har00ga** [comment]
Hey there, I can't seem to access either the first or the last link that is supplied in the original post. Do I lack permissions, or have they been relocated?

**Comment by Ivshti** [comment]
relocated
https://github.com/AdExNetwork/adex-protocol-eth/blob/master/contracts/Identity.sol
https://github.com/AdExNetwork/adex-protocol-eth/blob/master/js/IdentityProxyDeploy.js

same repo so you can't lack permissions

**Comment by har00ga** [comment]
Oops! Didn't notice it was the same repo. & Thanks. :slightly_smiling_face:

**Comment by Ivshti** [comment]
identity was updated since then, unassigning
